Add mqtt_bridge
wisniax/raptor_ws pull request #10
Opened 2024-04-19 15:46 UTC by bartbart2003

2024-05-01 19:44 UTC, wisniax requested changes
Haven't looked at the cpp files yet, nonetheless:
## Good Job ;)

Just address the comments please.

2024-05-01 19:44 UTC, wisniax commented on src/mqtt_bridge/msg/VescStatus.msg
> +Header header
Message redefinition from can_wrapper should be avoided. Topic described [here](https://answers.ros.org/question/261641/how-to-use-custom-defined-messages-in-another-package/)

2024-05-01 19:44 UTC, wisniax commented on src/mqtt_bridge/msg/Wheels.msg
> +Header header
Message redefinition from can_wrapper should be avoided. Topic described [here](https://answers.ros.org/question/261641/how-to-use-custom-defined-messages-in-another-package/)

2024-05-01 19:44 UTC, wisniax commented on src/mqtt_bridge/include/mqtt_bridge/ROSTopicHandler.hpp
> +  std::shared_ptr<mqtt::async_client> cli;
I think there is some convention in cpp, that we decided to follow, to start class variables with `m` prefix, for e.g. mCli

2024-05-01 19:44 UTC, wisniax commented on src/mqtt_bridge/include/mqtt_bridge/ROSTopicHandler.hpp
> +  void ROSTopicCallback_VescStatus(const mqtt_bridge::VescStatus::ConstPtr &receivedMsg);
Why sudden change of naming convention going forward? Also not sure u need to add `ROSTopic` prefix to a function already in the `ROSTopic` class cuz invoking it looks kinda sus

2024-05-03 14:16 UTC, AlvaroBajceps approved these changes
Please consider sorting *src/mqtt_bridge/include/mqtt_bridge/ROSTopicHandler.hpp*

No other concerns from me.

2024-05-05 16:37 UTC, wisniax approved these changes

2024-05-10 18:25 UTC, merged