Nowy environment i Dockerfile dla raptor_ws
wisniax/raptor_ws pull request #5
Opened 2024-01-08 21:02 UTC by Vynohradovv

Cześć, 

W ramach swojego zadania przygotowałem nową konfigurację środowiska dla vscode.
Dodałem Dockerfile i dodatkowo ustanowiłem pługin "Dev Containers", pozwalający pracować w środku Dockera. 
Sam obraz Dockera jest oparty na oficjalnej wersji ROS Noetic Desktop Full, można uruchomić turtlesim w środku Dockera z konsoli vscode.

![image](https://github.com/wisniax/raptor_ws/assets/50424297/54548eb5-417d-493e-93a9-2d85e0b5679a)

Mam nadzieję, że będzie pomocne. :)

2024-01-08 22:36 UTC, AlvaroBajceps commented
Pierwszy raz słyszę o _Dev Containers_-ach. W mojej opinii świetna propozycja.

2024-01-08 22:55 UTC, AlvaroBajceps commented on .devcontainer/Dockerfile
Jak próbowałem odpalić repo do debugowania, dostałem komunikat o braku debugera (gdb). Jak ręcznie doinstalowałem gdb (`apt install gdb`), wydaje się, że wszystko wystartowało jak powinno. 

**Proponuje instalować gdb przy budowaniu dokera.**

Aczkolwiek żaden ze mnie specialista. Może ja coś źle skonfigurowałem. W takim wypadku chcę zostać zprostowany. :)

2024-01-08 22:57 UTC, AlvaroBajceps requested changes
Oprócz małego problemiku z GDB naprawdę dobre środowisko.

2024-01-09 09:25 UTC, Vynohradovv commented on .devcontainer/Dockerfile
Dodałem `gdb` do pliku Dockerfile. Teraz debugowanie również działa z `git clone` :)

2024-01-09 09:58 UTC, AlvaroBajceps approved these changes
Jak dla mnie, nic więcej nie potrzeba.

2024-01-09 10:15 UTC, wisniax commented
Ogólnie świetna sprawa, więc GJ. Jak bawiłem się tym jeszcze z pół roku temu to nie działały dev-containery z UI, albo ja coś przekombinowałem...

Martwi mnie tylko usunięcie głównego `CMakeLists.txt`, który no niby jest symbolic linkiem, ale markuje główny src/ i cmake-a z którego chcemy korzystać.
Nawet jeśli teraz działa to nie musi w przyszłości (np. ktoś będzie miał na maszynie jeszcze inną konfigurację CMake-a, tak jak Ros ma swoją) + W pierwszym pierwszym [tutorialu](https://wiki.ros.org/ROS/Tutorials/CreatingPackage) do Ros-a jest to nawet zaznaczone
![image](https://github.com/wisniax/raptor_ws/assets/101927988/3d466aa1-709d-448b-8451-24131a8344fe)

2024-01-09 10:20 UTC, wisniax requested changes
https://github.com/wisniax/raptor_ws/pull/5#issuecomment-1882784717

2024-01-09 10:47 UTC, Vynohradovv commented
> Martwi mnie tylko usunięcie głównego `CMakeLists.txt`, który no niby jest symbolic linkiem, ale markuje główny src/ i cmake-a z którego chcemy korzystać. Nawet jeśli teraz działa to nie musi w przyszłości (np. ktoś będzie miał na maszynie jeszcze inną konfigurację CMake-a, tak jak Ros ma swoją) + W pierwszym pierwszym [tutorialu]

Główny `CMakeLists.txt` będzie tworzony w workspace, nie zależne Container to czy target, przy pierwszym uruchomieniu komendę `catkin_make` i będzie dedykowany do platformy tam gdzie chcemy użyć ten workspace. Właśnie dla tego został usunięty z repo. 

Jeżeli macie chwilę to proponuje przetestować.

2024-01-09 18:01 UTC, wisniax approved these changes
Well, prawda wsm. Zobaczymy, najwyżej się poprawkę strzeli :)
Good Job 👍

2024-01-09 18:03 UTC, merged